### ISSUE TITLE
LICENCE

### ISSUE THREAD

**Issue by prydie** [cesarve77/select2-materialize#1]
Thanks for the great work.

Would you be happy to explicitly release the work under an open licence (MIT, BSD)? If so adding a `LICENCE` file to the root of the repository would be great.

**Comment by cesarve77** [comment]
I update read, with Do whatever you want,
That's good enough?

**Comment by prydie** [comment]
Would you mind adding a recognised licence (e.g. https://opensource.org/licenses/MIT). Protects you and people using your project :)

**Comment by cesarve77** [comment]
Ready, just checkout the note at end of licence.
